name: 'New version'
description: 'Calculate the new version based on bump'
inputs:
  bump_version:
    description: 'The bump to apply'
    required: true
outputs:
  found:
    description: "Indicate if a new version was calculated"
    value: ${{ !!steps.match.outputs.result }}
  value:
    description: "The new version"
    value: ${{ steps.match.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Install gem-release
      shell: bash
      run: gem install gem-release
    - name: Pretend bump version
      id: bump_version
      shell: bash
      run: |
        OUTPUT=$(gem bump --pretend --no-commit --version ${{ inputs.bump_version }})
        echo "output=$OUTPUT" >> $GITHUB_OUTPUT
    - name: Run gem bump pretend
      id: match
      uses: actions/github-script@v7
      env:
        BUMP_VERSION_OUTPUT: ${{ steps.bump_version.outputs.output }}
      with:
        script: |
          const output = process.env.BUMP_VERSION_OUTPUT;
          const regexPattern = new RegExp('^[Bb]ump.* ([^ ]+)$', "m");
          const match = output.match(regexPattern);
          core.debug(`Match: ${match}`);
          if (match) {
            const result = match[1];
            core.debug(`Result: ${result}`);
            return result;
          } else {
            core.setFailed(`New version not found`);
            return null;
          }
