plugins:
  - rubocop-performance # https://docs.rubocop.org/rubocop-performance/cops_performance.html
  - rubocop-rspec # https://docs.rubocop.org/rubocop-rspec/cops_rspec.html

# Cops documented: https://docs.rubocop.org/rubocop/1.36/cops_style.html
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Layout/LineLength:
  Max: 150

Lint/ElseLayout:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - lib/uncov.rb

Metrics/ParameterLists:
  Max: 6

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Exclude:
    - lib/uncov.rb
