name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
      - name: Recheck required labels
        run: gh workflow run enforce-labels.yml -f pr-number=${{ github.event.number }}
        env:
          GH_TOKEN: ${{ github.token }}