name: "Enable auto-merge on dependabot PRs"
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{github.event.pull_request.html_url}}
