name: Changelog

on:
  workflow_call:
    outputs:
      changelog:
        description: "The generated changelog content"
        value: ${{ jobs.changelog.outputs.changelog }}
      current_version:
        description: "The current version"
        value: ${{ jobs.changelog.outputs.current_version }}
      new_version:
        description: "The new version"
        value: ${{ jobs.changelog.outputs.new_version }}
      version_bump:
        description: "The version bump type (major, minor, patch)"
        value: ${{ jobs.changelog.outputs.version_bump }}
      releasable:
        description: "Whether there are releasable changes"
        value: ${{ jobs.changelog.outputs.releasable }}
  workflow_dispatch:
  push:
    branches: ['develop']

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
      current_version: ${{ steps.current_version.outputs.current_version }}
      new_version: ${{ steps.new_version.outputs.group1 }}
      version_bump: ${{ steps.version_bump.outputs.lowercase }}
      releasable: ${{ steps.version_bump_match.outputs.match != '' && steps.new_version.outputs.group1 != '' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gem-release
        run: gem install gem-release

      - name: Determine current version
        id: current_version
        run: |
          CURRENT_VERSION=$(ruby -e "require './lib/uncov/version'; puts Uncov::VERSION")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "categories": [
                { "title": "### Major", "labels": ["release:breaking"] },
                { "title": "### Minor", "labels": ["release:feature"] },
                { "title": "### Patch", "labels": ["release:fix"] }
              ],
              "ignore_labels": ["release:ignore"],
              "pr_template": "- [##{{NUMBER}}](#{{URL}}): #{{TITLE}}, by [@#{{AUTHOR}}](https://github.com/#{{AUTHOR}})"
            }
          fromTag: "v${{ steps.current_version.outputs.current_version }}"
          toTag: "HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect version bump
        uses: actions-ecosystem/action-regex-match@v2
        id: version_bump_match
        with:
          text: ${{ steps.changelog.outputs.changelog }}
          regex: '^### (Major|Minor|Patch)$'
          flags: m

      - name: Lowercase version bump
        if: ${{ steps.version_bump_match.outputs.group1 }}
        id: version_bump
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ steps.version_bump_match.outputs.group1 }}

      - name: Bump version output
        if: ${{ steps.version_bump_match.outputs.group1 }}
        id: bump_version_output
        run: |
          NEW_VERSION=$(gem bump --pretend --no-commit --version ${{ steps.version_bump.outputs.lowercase }})
          echo "bump_version_output=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: New version
        if: ${{ steps.version_bump_match.outputs.group1 }}
        uses: actions-ecosystem/action-regex-match@v2
        id: new_version
        with:
          text: ${{ steps.bump_version_output.outputs.bump_version_output }}
          regex: '^[Bb]ump.+ ([^ ]+)$'
          flags: m

      - name: Add job summary - changelog
        if: ${{ steps.version_bump_match.outputs.group1 }}
        run: |
          echo -e '# Current version: ${{ steps.current_version.outputs.current_version }}\n\n' > $GITHUB_STEP_SUMMARY
          echo -e '# Version bump: ${{ steps.version_bump.outputs.lowercase }}\n\n' >> $GITHUB_STEP_SUMMARY
          echo -e '# New version: ${{ steps.new_version.outputs.group1 }}\n\n' >> $GITHUB_STEP_SUMMARY
          echo -e '# Releasable: ${{ steps.version_bump_match.outputs.match != '' && steps.new_version.outputs.group1 != '' }}\n\n' >> $GITHUB_STEP_SUMMARY
          echo -e '# Changelog\n${{ steps.changelog.outputs.changelog }}' >> $GITHUB_STEP_SUMMARY


      - name: Add job summary - no changes
        if: ${{ !steps.version_bump_match.outputs.group1 }}
        run: |
          echo -e '# No changes' >> $GITHUB_STEP_SUMMARY
