name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_call:
  # This allows other workflows to call this one

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # We need the full git history for diffs

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: COVERAGE=1 bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rake lint
