name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize, auto_merge_enabled]
  workflow_dispatch:
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - name: Delay for autolabel-pr.yml to work
        run: sleep 3s

      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: "release:ignore,release:fix,release:feature,release:breaking"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
