name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize, auto_merge_enabled]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: "release:ignore,release:fix,release:feature,release:breaking"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
