name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Action Release"
          git config user.email "actions@github.com"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gem-release
        id: prepare
        uses: ./.github/workflows/changelog.yml

      - name: No changes failure
        if: ${{ !steps.prepare.outputs.relasable }}
        run: exit 1

      - name: Bump version
        id: bump_version
        run: |
          gem bump --no-commit --version ${{ steps.prepare.outputs.version_bump }}
          # Get the new version after bumping
          NEW_VERSION=$(ruby -e "require './lib/uncov/version'; puts Uncov::VERSION")
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update Gemfile.lock gem version
        run: |
          bundle config set frozen false
          bundle install

      - name: Update CHANGELOG.md
        run: |
          VERSION="${{ steps.prepare.outputs.new_version }}"
          DATE=$(date +"%Y-%m-%d")
          CHANGELOG_ENTRY="## [$VERSION] - $DATE\n\n${{ steps.prepare.outputs.changelog }}\n"
          echo -e "# Changelog\n\n$CHANGELOG_ENTRY" > CHANGELOG_NEW.md
          [ -f CHANGELOG.md ] && tail -n +2 CHANGELOG.md >> CHANGELOG_NEW.md
          mv CHANGELOG_NEW.md CHANGELOG.md

      - name: Git push changes
        run: |
          git add Gemfile.lock CHANGELOG.md lib/uncov/version.rb
          git commit -m "Prepare release v${{ steps.prepare.outputs.new_version }}"
          git push

      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Release
        run: |
          gem release --tag --push --github -d "${{ steps.prepare.outputs.changelog }}" --token "${{ secrets.GITHUB_TOKEN }}"
