name: Release

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Prepare changelog and version
    uses: ./.github/workflows/changelog.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: changelog
    steps:
      - name: No changes failure
        if: ${{ needs.changelog.outputs.releasable != 'true' }}
        run: exit 1

      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Action Release"
          git config user.email "actions@github.com"

      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gem-release
        run: gem install gem-release

      - name: Bump version
        run: gem bump --no-commit --version ${{ needs.changelog.outputs.version_bump }}

      - name: Update Gemfile.lock gem version
        run: |
          bundle config set frozen false
          bundle install

      - name: Build help output
        id: help
        run: |
          {
            echo 'output<<EOF'
            bundle exec uncov -h
            echo 'EOF'
          } | tee -a "$GITHUB_OUTPUT"

      - name: Update README.md with the new help output
        id: readme_update
        uses: ./.github/actions/multiline_regexp_replace_in_file
        with:
          file_name: README.md
          pattern: '^(### Display configuration options\n```bash\n)[\s\S]*?(```)'
          replace: '$1${{steps.help.outputs.output}}$2'

      - name: Build version header
        id: changelog_version_header
        run: |
          VERSION="v${{ needs.changelog.outputs.new_version }}"
          STRING="$(date +"%Y-%m-%d"): [$VERSION](https://github.com/mpapis/uncov/releases/tag/$VERSION)"
          echo "string=$STRING" | tee -a $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        id: changelog_update
        uses: ./.github/actions/multiline_regexp_replace_in_file
        with:
          file_name: CHANGELOG.md
          pattern: '^# Changelog\n\n'
          replace: |
            # Changelog
            
            ## ${{steps.changelog_version_header.outputs.string}}
            
            ${{ needs.changelog.outputs.changelog }}
            

      - name: DEBUG STOP
        run: |
          echo README changed: ${{ steps.readme_update.outputs.replaced }}
          echo CHANGELOG changed: ${{ steps.changelog_update.outputs.replaced }}
          git diff
          exit 128

      - name: Git push changes
        run: |
          git add lib/uncov/version.rb Gemfile.lock README.md CHANGELOG.md
          git commit -m "Release v${{ needs.changelog.outputs.new_version }}"
          git push

      - name: Release
        run: |
          gem release --tag --push --github -d "${{ needs.changelog.outputs.changelog }}" --token "${{ secrets.GITHUB_TOKEN }}"
