name: Release

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Prepare changelog and version
    uses: ./.github/workflows/changelog.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: changelog
    steps:
      - name: No changes failure
        if: ${{ needs.changelog.outputs.releasable != 'true' }}
        run: exit 1

      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Action Release"
          git config user.email "actions@github.com"

      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gem-release
        run: gem install gem-release

      - name: Bump version
        run: gem bump --no-commit --version ${{ needs.changelog.outputs.version_bump }}

      - name: Update Gemfile.lock gem version
        run: |
          bundle config set frozen false
          bundle install

      - name: Update README.md - Display configuration options
        run: |
          ruby -i'' -ne "
            BEGIN { in_target_section = false; in_code_block = false }
            if /^### Display configuration options$/
              in_target_section = true
              print
              next
            elsif in_target_section && /^\`\`\`bash$/
              in_code_block = true
              puts '\`\`\`bash'
              puts '\$ uncov -h'
              puts '$(uncov -h)'
              next
            elsif in_code_block && /^\`\`\`$/
              in_code_block = false
              in_target_section = false
              puts '\`\`\`'
              next
            end
            print unless in_code_block
          " README.md

      - name: Update CHANGELOG.md
        run: |
          VERSION="v${{ needs.changelog.outputs.new_version }}"
          cat << EOF > CHANGELOG_NEW.md
          # Changelog
          
          ## $(date +"%Y-%m-%d"): [$VERSION](https://github.com/mpapis/uncov/releases/tag/$VERSION)
          
          ${{ needs.changelog.outputs.changelog }}
          
          EOF
          [ -f CHANGELOG.md ] && tail -n +3 CHANGELOG.md >> CHANGELOG_NEW.md
          mv CHANGELOG_NEW.md CHANGELOG.md

      - name: Git push changes
        run: |
          git add lib/uncov/version.rb Gemfile.lock README.md CHANGELOG.md
          git commit -m "Release v${{ needs.changelog.outputs.new_version }}"
          git push

      - name: Release
        run: |
          gem release --tag --push --github -d "${{ needs.changelog.outputs.changelog }}" --token "${{ secrets.GITHUB_TOKEN }}"
