name: Tag Version

on:
  push:
    branches:
      - main
    paths:
      - 'lib/uncov/version.rb'

permissions:
  contents: write
  pull-requests: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    if: github.repository == 'mpapis/uncov'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Extract version
        id: version
        run: |
          VERSION=$(ruby -e "require './lib/uncov/version'; puts Uncov::VERSION")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
